import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "./components/NextAuthProviders";

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by Gautam",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
